# 공통설정

--- # local 설정
spring:
  config:
    activate:
      on-profile: "security-local"
  security:
    oauth2:
      client:
        registration:
          naver:
            redirect-uri: http://localhost:8778/oauth2/callback/naver
            authorization-grant-type: authorization_code
            client-secret: '123123'
            client-id: '123123'
            client-name: Naver
          kakao:
            client-authentication-method: POST
            redirect-uri: http://localhost:8778/oauth2/callback/kakao
            authorization-grant-type: authorization_code
            client-id: '123123'
            scope: account_email,profile_nickname
            client-name: Kakao
          google:
            redirect_uri: http://localhost:8778/oauth2/callback/google
            client-secret: '123123'
            client-id: '123123'
            scope: profile,email
        provider:
          kakao:
            user-name-attribute: id
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
          naver:
            user-name-attribute: response
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            user-info-uri: https://openapi.naver.com/v1/nid/me
            token-uri: https://nid.naver.com/oauth2.0/token

cors:
  allowed-origins: 'http://localhost:3000'
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: '*'
  max-age: 3600

--- #dev 설정
spring:
  config:
    activate:
      on-profile: "security-dev"