spring:
  jpa:
    defer-datasource-initialization: true
    show-sql: false
    open-in-view: false
    database-platform: MYSQL
    hibernate:
      ddl-auto: none
      #use-new-id-generator-mappings: true
    properties:
      hibernate.format_sql: true
      hibernate.show_sql: false
      hibernate.dialect: org.hibernate.dialect.MySQL57Dialect
      hibernate.default_fetch_size: ${chunkSize:100}
      hibernate.connection.provider_disables_autocommit: true
      hibernate.jdbc.batch_size: ${chunkSize:100}
      hibernate.order_inserts: true
      hibernate.order_updates: true

--- # local 설정
spring:
  config:
    activate:
      on-profile: "db-local"

  jpa:
    show-sql: true
    #database-platform: H2
    hibernate:
      ddl-auto: create

  datasource:
    hikari:
      maxLifetime: '2000000'
      connectionTimeout: '30000'
      minimumIdle: '5'
      maximumPollSize: '20'
      idleTimeout: '30000'
      pollName: SpringBootJPAHikariCP
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3002/greatseo?autoReconnect=true
    username: 'greatseo'
    password: 'greatseo'

--- # dev 설정
spring:
  config:
    activate:
      on-profile: "db-dev"

  jpa:
    hibernate:
      ddl-auto: update

  datasource:
    hikari:
      maxLifetime: '2000000'
      connectionTimeout: '30000'
      minimumIdle: '5'
      maximumPollSize: '20'
      idleTimeout: '30000'
      pollName: SpringBootJPAHikariCP
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3002/greatseo?autoReconnect=true
    username: 'greatseo'
    password: 'greatseo'