# 공통설정

--- # local 설정
spring:
  config:
    activate:
      on-profile: "key-local"


# jwt secret key 설정
oauth:
  jwt:
    secret: '8sknjlO3NPTBqo319DHLNqsQAfRJEdKsETOd12312312321321s'
  authorizedRedirectUri: http://localhost:3000/oauth/redirect


# 토큰 관련 secret Key 및 RedirectUri 설정
app:
  auth:
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
    tokenExpiry: 1800000
    refreshTokenExpiry: 604800000
  oauth2:
    authorizedRedirectUri:
      #- http://localhost:3000/oauth/redirect

--- #dev 설정
spring:
  config:
    activate:
      on-profile: "key-dev"

